ALTER TABLE plan_sections
  ADD COLUMN IF NOT EXISTS ai_generatable BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS auto_fill BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS auto_fill_source VARCHAR(50),
  ADD COLUMN IF NOT EXISTS data_dependencies JSONB NOT NULL DEFAULT '[]';
